apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: front
spec:
  ingressClassName: nginx
  rules:
  - host: bearsnack.store
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-deploy-svc
            port:
              number: 80
